IF 
  Global("WIYeslConlanSmith","ID2103",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("lk#yeslk")
  InMyArea("lk#yeslk")
  !StateCheck("lk#yeslk",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIYeslConlanSmith","ID2103",1)
	DisplayString("lk#yeslk",@550 /* A modest smithy, but a steady craftsman needs naught but their hammer and a stoking fire tae do Moradin proud. Aye, plenty of fine crafts to honor the gods here. */)
END
