IF
  Global("WIYislDDMoraTemp","ID6004",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("lk#yeslk")
  InMyArea("lk#yeslk") 
  !StateCheck("lk#yeslk",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIYislDDMoraTemp","ID6004",1)
	DisplayString("lk#yeslk",@1800 /* *gasp* Will ye look at that. A forge temple to the greatest of me gods. But blast and damnation, it ain't right fer it tae be so cold. Molten metal should be alightin' the room with Moradin's favor. What damnable curse has taken its warmth so? */)
END
