IF
  Global("WIBranBuriIsle","ID9300",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Branwen")
  InMyArea("Branwen")
  !StateCheck("Branwen",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIBranBuriIsle","ID9300",1)
	DisplayString("Branwen",@2500 /* Watch thy step and show care. These are the honored dead of the children of Tempus and we must always be respectful. May he forgive us for even this brief trespass. */)
END
