IF
  Global("WIRasaGloomfrost2","ID9502",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Rasaad")
  InMyArea("Rasaad") 
  !StateCheck("Rasaad",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIRasaGloomfrost2","ID9502",1)
	DisplayString("Rasaad",@2650 /* We may be entombed beneath an ocean of ice, yet I cannot help but feel that this is some place holy. The light of the sun grows soft here, yet its illumination is multiplied ten fold. */)
END

IF
  Global("WISafaGloomfrost2","ID9502",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Safana")
  InMyArea("Safana") 
  !StateCheck("Safana",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WISafaGloomfrost2","ID9502",1)
	DisplayString("Safana",@2651 /* These caves are more gorgeous than any gemstone I've ever seen. If only it could be condensed down into one big diamond, we'd be richer than any king. */)
END
