IF
  Global("WISkieGerthShop","ID2113",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InMyArea("L#2SDSkie") 
  InParty("L#2SDSkie")
  !StateCheck("L#2SDSkie",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WISkieGerthShop","ID2113",1)
	DisplayString("L#2SDSkie",@750 /* You don't suppose this shop has some souvenirs? Maybe I could get a carving from the wood or oh a cloak made of leaves from it! My friends back home will be SO jealous. */)
END
