// Xan

	ACTION_IF (FILE_EXISTS_IN_GAME ~7XXANJ.dlg~) BEGIN
		// Dialog
		COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
			REPLACE_TEXTUALLY ~// BG1inBG2 == 7XXANJ~ ~== 7XXANJ~

		// Scripts 7XXAN
		EXTEND_TOP ~ID4001.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XXAN/ID4001.baf~

				PRINT ~
				Xan : BG1 NPC in BG2 (Smiling Imp and Austin) is installed
				~
				
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~O#XANJ.dlg~) BEGIN
		// Dialog
		COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
			REPLACE_TEXTUALLY ~// Xan for BG2 == O#XANJ~ ~== O#XANJ~

		// Scripts
		EXTEND_TOP ~ID4001.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/O#XAN/ID4001.baf~

				PRINT ~
				Xan : for BG2 (Kulyok) is installed
				~
	END

// Baeloth

	ACTION_IF (FILE_EXISTS_IN_GAME ~ZDBAEJ.dlg~) BEGIN
		// Dialog
			COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
				REPLACE_TEXTUALLY ~// Baeloth BG2 == ZDBAEJ~ ~== ZDBAEJ~

		// Scripts
		EXTEND_TOP ~ID9100.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/ZDBAE/ID9100.baf~
		EXTEND_TOP ~ID4000.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/ZDBAE/ID4000.baf~

				PRINT ~
				Baeloth : in BG2 (Dark0dave) is installed
				~
		END

// Skie / Eldoth

	ACTION_IF (FILE_EXISTS_IN_GAME ~7XEldoJ.dlg~) AND (FILE_EXISTS_IN_GAME ~7XSkiJ.dlg~) BEGIN
		// Dialog
			COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
				REPLACE_TEXTUALLY ~// BG1inBG2 == 7XSkiJ~ ~== 7XSkiJ~
				REPLACE_TEXTUALLY ~// BG1inBG2 == 7XEldoJ~ ~== 7XEldoJ~

		// Scripts Skie 7XSKI
		EXTEND_TOP ~ID1007.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XSKI/ID1007.baf~
		EXTEND_TOP ~ID2113.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XSKI/ID2113.baf~

		// Scripts Eldoth 7XELDOT
		EXTEND_TOP ~ID2114.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XELDOT/ID2114.baf~
		EXTEND_TOP ~ID9101.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XELDOT/ID9101.baf~

				PRINT ~
				Skie and Eldoth : BG1 NPC in BG2 (Smiling Imp and Austin) are installed
				~
	END

// Alora

	ACTION_IF (FILE_EXISTS_IN_GAME ~7XALORAJ.dlg~) BEGIN
		// Dialog
		COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
			REPLACE_TEXTUALLY ~// BG1inBG2 == 7XALORAJ~ ~== 7XALORAJ~

		// Scripts 7XALORA
		EXTEND_TOP ~ID2001.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XALORA/ID2001.baf~
		EXTEND_TOP ~ID3000.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XALORA/ID3000.baf~
		EXTEND_TOP ~ID7005.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XALORA/ID7005.baf~

				PRINT ~
				Alora : BG1 NPC in BG2 (Smiling Imp and Austin) is installed
				~
				
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~CMALORAJ.dlg~) BEGIN
		// Dialog
		COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
			REPLACE_TEXTUALLY ~// Alora for BG2 == CMALORAJ~ ~== CMALORAJ~

		// Scripts CMAlora
		EXTEND_TOP ~ID2001.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/CMAlora/ID2001.baf~
		EXTEND_TOP ~ID3000.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/CMAlora/ID3000.baf~
		EXTEND_TOP ~ID7005.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/CMAlora/ID7005.baf~

				PRINT ~
				Alora : for BG2 (Raven) is installed
				~
	END

// Yeslick

	ACTION_IF (FILE_EXISTS_IN_GAME ~lk#yesj.dlg~) BEGIN
		// Dialog
		COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
			REPLACE_TEXTUALLY ~// Yeslick for BG2 == lk#yesj~ ~== lk#yesj~

		// Scripts lk#yeslk
		EXTEND_TOP ~ID1001.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/lk#yeslk/ID1001.baf~
		EXTEND_TOP ~ID2103.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/lk#yeslk/ID2103.baf~
		EXTEND_TOP ~ID6004.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/lk#yeslk/ID6004.baf~
		EXTEND_TOP ~ID6013.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/lk#yeslk/ID6013.baf~

				PRINT ~
				Yeslick : NPC for BG2 (Pixel Kaiser, K'aeloree and Lava Del'Vortel) is installed
				~
				
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~7XYESJ.dlg~) BEGIN
		// Dialog
		COPY ~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~	~weidu_external/iwd_eet-party-banter/Dialogue/Interject.d~
			REPLACE_TEXTUALLY ~// BG1inBG2 == 7XYESJ~ ~== 7XYESJ~

		// Scripts 7XYES
		EXTEND_TOP ~ID1001.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XYES/ID1001.baf~
		EXTEND_TOP ~ID2103.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XYES/ID2103.baf~
		EXTEND_TOP ~ID6004.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XYES/ID6004.baf~
		EXTEND_TOP ~ID6013.bcs~ ~iwd_eet-party-banter/Party-banter_for-all/7XYES/ID6013.baf~

				PRINT ~
				Yeslick : BG1 NPC in BG2 (Smiling Imp and Austin) is installed
				~
	END


/*
		// Scripts
		COPY ~iwd_eet-party-banter/Scripts/ID4001.baf~ ~weidu_external/iwd_eet-party-banter/Scripts/O#XAN/ID4001.baf~
			REPLACE_TEXTUALLY ~"Xan"~ ~"O#XAN"~
		EXTEND_TOP ~ID4001.bcs~ ~weidu_external/iwd_eet-party-banter/Scripts/O#XAN/ID4001.baf~

				PRINT ~
				Xan : for BG2 (Kulyok) is installed
				~
*/
