IF 
  Global("WIBranTempleTempus","ID1001",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Branwen")
  InMyArea("Branwen")
  !StateCheck("Branwen",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIBranTempleTempus","ID1001",1)
	DisplayString("Branwen",@100 /* As fine a temple to Tempus as I ever have seen! Temples to the god of war are usually of a simple make, but here in the north, reverence to him seems on a much grander scale! Oh will you look at those pillars and the engravings… and *gasp* upon the statue that dominates the apse! Never have I seen the figure of Tempus brought so much to life before mine eyes! How does such a small town hold such a wonder as this? I must insist we stop to properly pay our respects. */)
END

IF
  Global("WIYeslTempleTempus","ID1001",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InMyArea("Yeslick")
  InParty("Yeslick")
  !StateCheck("Yeslick",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIYeslTempleTempus","ID1001",1)
	DisplayString("Yeslick",@101 /* A temple to Tempus is it? Among ye humans I believe he is much the same as me own Clangeddin. And yet, rarely do ye see worshippers of th’ two meet in peace. T’would be grand if we could all get together and discuss matters of war in peace. */)
END

IF
  Global("WIAnomTempleTempus","ID1001",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InMyArea("Anomen")  
  InParty("Anomen")
  !StateCheck("Anomen",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WIAnomTempleTempus","ID1001",1)
	DisplayString("Anomen",@102 /* An impressive temple for so remote a location. I’ve never felt much comfort among worshippers of Tempus however. Battle is a necessary thing at times, certainly, but the worship of it for its own merit seems... foolish to me. */)
END
