IF
  Global("WISkiePomabEmp","ID1007",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("7XSKI")
  InMyArea("7XSKI")
  !StateCheck("7XSKI",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WISkiePomabEmp","ID1007",1)
	DisplayString("7XSKI",@250 /* Well, this place is nice? Do you think they have some wax balm here? My lips are just really chapped. How long do you think we're going to be up in the north? Not that I don't like traveling! It's not like I want to go back home or anything it's just... uhh... it's just really far away... */)
END
